### ISSUE TITLE
 ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by maneeshmp** [flowdock/flowdock-git-hook#9]
I am getting below error while installing flowdock-git-hook in gitlab 7.13 version
gem version - 2.2.5
ruby version - 2.1.0

maneesh:/opt/gitlab/embedded/bin$ sudo ./gem install flowdock-git-hook 
Building native extensions.  This could take a while...
ERROR:  Error installing flowdock-git-hook:
        ERROR: Failed to build gem native extension.

    /opt/gitlab/embedded/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean
sh: 1: make: not found

make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/posix-spawn-0.3.11 for inspection.
Results logged to /opt/gitlab/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/posix-spawn-0.3.11/gem_make.out

**Comment by RedBulli** [comment]
This doesn't seem to be related to the flowdock-git-hook. It seems that you are missing build tools (make).

GitLab has a Flowdock integration built in which you can use. https://www.flowdock.com/help/gitlab
